### ISSUE TITLE
画面デザインおよび画面遷移のラフ画を作成する

### ISSUE THREAD

**Issue by mune-actor-en** [mune92283498/uchinoko_project#1]

**Comment by y-mabuchi** [comment]
おー、仕事が早いっすね！

コラボレーターで参加しました。

画面設計よろしくお願いします！

こちらでラフ画を共有しながらいけそうですね！

**Comment by mune-actor-en** [comment]
参加ありがとうございます〜
とりあえず作っておこうかなと！
Slackにしようかと思ってましたけど、こっちで管理できた方が一元化できて良さそうですね！
Markdownで画像貼り付けられるからイイですね。

**Comment by y-mabuchi** [comment]
画面数のメモです

1. サインイン画面
2. ログイン画面
3. うちの子登録画面
4. うちの子一覧画面
5. 投稿画面
6. 投稿編集画面
7. タイムライン画面（たまらんボタン、SNSシェアボタン）

**Comment by mune-actor-en** [comment]
1. サインアップ画面
![1 サインアップ画面](https://user-images.githubusercontent.com/46050182/99400438-4cdf4d00-292a-11eb-9e69-ddc8f8f90ec5.jpg)
1. ログイン画面
![2 ログイン画面](https://user-images.githubusercontent.com/46050182/99400451-54065b00-292a-11eb-961c-10230c12a82c.jpg)
1. うちの子登録画面
![3 うちの子登録画面](https://user-images.githubusercontent.com/46050182/99400480-5a94d280-292a-11eb-981f-93ed6775efbf.jpg)

雑ですが、こんなイメージですかね。
キーカラーはこちらです。
[Color Hunt](https://colorhunt.co/palette/220258)

**Comment by y-mabuchi** [comment]
https://www.figma.com/resources/assets/material-design-themeing-ui-kit/

figma用のmaterial-uiプラグインを見つけてしまいました

**Comment by y-mabuchi** [comment]
7. タイムライン画面
![IMG_20201118_094954](https://user-images.githubusercontent.com/5494890/99468315-a0ca5000-2983-11eb-977f-49884fa1f0a9.jpg)

ヘッダーを用意して、ロゴ（もしくはアプリ名）とハンバーガーメニューはあったほうが良いと思いました！

ちなみにトラハックさんのアプリ開発動画の丸パクリですｗ
元ネタは
https://youtu.be/IBL4CTPoe4M
こちらです

タイムラインの1投稿は、Material-UIのCardコンポーネント
https://material-ui.com/components/cards/

ヘッダーは、Material-UIのAppBarコンポーネント
https://material-ui.com/components/app-bar/
です

**Comment by mune-actor-en** [comment]
figma用のMaterialーUIプラグインってあるんですね！！
早速入れてみました🤗
よく使い方はわかっていませんが😂笑
ありがとうございます！

タイムライン画面設計してくれてる👀
ありがとうございます〜😭
トラハックさんのリンクもありがとうございます！
前に参考になるな〜と思って忘れていた部分もあったので、改めて見直して設計に反映させようと思います😊
やっぱりMaterial-UIのデザインいいですね！
基本的なレイアウトはこれでOKだと思います！

**Comment by y-mabuchi** [comment]
今日、時間作って投稿画面を書いてみます！

Figmaの編集ですが、共同作業者に招待いただければ、一緒に作業できます

よろしくお願いします！

やり方は

https://chot.design/figma-beginner/e5ffe7ae3d24/

が参考になると思います。

**Comment by mune-actor-en** [comment]
今日は本業で作業できませんでした😂
ありがたいー😭✨
おぉ！自分で調べたFigmaの使い方よりもわかりやすい！！笑
早速招待します！！

[Uchinoko画面レイアウト](https://www.figma.com/file/6Yz9LFWH4Qyv5dcFKMxhh8/Uchinoko%E7%94%BB%E9%9D%A2%E3%83%AC%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88?node-id=34786%3A29337)

**Comment by y-mabuchi** [comment]
![IMG_20201120_153737](https://user-images.githubusercontent.com/5494890/99771935-41b83700-2b4d-11eb-9cca-7a1e43d6d061.jpg)


かんたんですが、投稿画面です

編集画面は使い回せばいけそうな感じかと思います！

**Comment by mune-actor-en** [comment]
ありがとうございます！！
じゃあ残りの画面設計は「うちの子一覧画面」だけですかね。

簡単ですが、とりあえずロゴ 作ってみました〜
![Uchinoko-Logo](https://user-images.githubusercontent.com/46050182/99807634-210ad400-2b83-11eb-8e7a-42223745cde7.png)

**Comment by y-mabuchi** [comment]
ロゴよいですね！

うちの子一覧は、Material-UIのCardコンポーネントにあるMediaを使えば、それっぽくなる気がしました〜

https://material-ui.com/components/cards/

いくつかやることがあるなー、と思うのでリストにしますね

- 開発環境の作成（フォルダ構成など）
- Firebaseプロジェクトの作成
- DB設計
- API設計
- トラハックさん招待
- ブランチ戦略の決定
- 各画面の担当割り振り→issueに
- GitHub→Slack通知（必要なら
- 開発の進め方
- 情報共有用のGoogleドライブ作成（追記

う、、、けっこうあるw

ちなみにトラハックさん、コードレビューで参加いただけるとラジオでおっしゃってました！

**Comment by mune-actor-en** [comment]
おぉー確かにいい感じに画像が表示されるし、シェア機能も備えてていい感じですね！
やりがいがありますね！笑
「ブランチ戦略」ってのはどういったものですか？

おぉ！それは心強いですね！！
コードレビューしてもらうとコーディング力がさらに身につきそうですね！

**Comment by y-mabuchi** [comment]
ブランチ戦略は、複数人で開発するときに、みんながmasterにコミットすると、カオスになるのでw、どんなブランチを切って作業するかの決まりごとって感じです

たとえば

- master（いつでもデプロイ可能）
- develop（普段の作業用）

をまず用意して、作業者は、developブランチから

- feature-hoge(#issue番号)

みたいな作業ブランチを切って作業

コミット&プッシュしたらプルリクエスト、誰かがレビューしてdevelopにマージ


って感じです！

私が個人で開発してるリポジトリです、参考まで

https://github.com/y-mabuchi/rotory-on

**Comment by mune-actor-en** [comment]
あーなるほど！そういうことですか！
確かに仕事でもさすがにいきなりmasterブランチに資源投げ込まないですね笑
現場だと「名前 + 日付 画面名」みたいな運用してますね。

**Comment by mune-actor-en** [comment]
うちの子一覧画面はゆーすけさんのアドバイスを参考にこんな感じにしてみました！
- PC版：Material-UIのCardコンポーネント「Media」
- スマホ版：Material-UIのApp Barコンポーネント「Bottom App Bar」
<img width="589" alt="うちの子一覧画面" src="https://user-images.githubusercontent.com/46050182/99926196-33a02b80-2d84-11eb-9a88-522a75675d5d.png">

- [Media](https://material-ui.com/components/cards/#media)
- [Bottom App Bar](https://material-ui.com/components/app-bar/#bottom-app-bar)
