### ISSUE TITLE
APIの仕様をwikiにまとめる

### ISSUE THREAD

**Issue by y-mabuchi** [mune92283498/uchinoko_project#20]
- [ ] Postsリソース
- [ ] うちの子リソース

**Comment by y-mabuchi** [comment]
@gonta1026 
取り急ぎ、認証とUsersリソースについてまとめました！

投稿とうちの子リソースについては、今週末でまとめちゃう予定です。

お手すきのときにチラッとご確認ください〜

https://github.com/mune-actor-en/uchinoko-project/wiki/API%E4%BB%95%E6%A7%98

**Comment by gonta1026** [comment]
@y-mabuchi 
ご対応ありがとうございます！！
こちらWikiにまとめていただいたと思うのですが、当初のスプレッドシートにはまとめない感じでしょうか？？
おそらく、RequestやResponseのデータが今後変わることや扱うデータが増えることを考えると当初のスプレッドシートにまとめていただいた方がいいと思っています！
あと、縦に大きくスクロールさせる必要があり、全体的な情報が少し見づらいかなと思いました💦
中身以外のところで注文をつけて申し訳ないです🙇‍♂️

**Comment by y-mabuchi** [comment]
@gonta1026 

いえいえ！
確認ありがとうございます！

wikiにまとめたのは、GitHubに情報を集約したほうが、フロントを担当される方が確認しやすいかなー、と思ったからです

スプレッドシートとwiki、どっちがいいですかねえ、、、

みなさんの意見を聞いて判断したい感じですね

縦長なのはおっしゃるとおり😅

リソースごとにページを分けるくらいですかねえ

そう考えると、スプレッドシートのほうがよいような、、、w

**Comment by gonta1026** [comment]
@y-mabuchi 

なるほどです！
フロントエンドの方を含めて情報をみる時にWikiを通すという点は確かにそうですね！！
それではWikiにスプレッドシートのリンクだけ貼っといてそこからスプレッドシートに飛ばして見てもらうとかどうですかね？？
うちの会社はそうしています！
でもせっかく作っていただいたのでこちらの運用でも大丈夫です🙇‍♂️

**Comment by y-mabuchi** [comment]
いいですね！

ではwikiにリンク貼って、スプレッドシート管理で行きましょう！

**Comment by y-mabuchi** [comment]
スプレッドシート管理に移行したので、closeします。
