### ISSUE TITLE
  tsconfig.json の２１行目が、自動修正される件

### ISSUE THREAD

**Issue by koyama223y** [mune92283498/uchinoko_project#26]
（概要）
私の環境（windows10 / vscode / github desktop)にて、以下の現象が起きます。
yarn start を実行すると、tsconfig.json の２１行目が、自動修正されます。
＜修正前＞"jsx": "react"
＜修正後＞"jsx": "react-jsx"
そのため、クローンやフォークをしても、毎回、コミットしなければならず、
仕方ないので、コミットするわけですが、
その後、github desktop を起動すると、毎回、プルリクを催促されます。

（現象の詳細）
１：まずフォークして、クローンしました。
２：yarn start すると、react-scripts がないというエラーメッセージが出る。
　　(windows10 / vsconde のターミナルで、実行）
３：なので、yarn install を行う。
４：再度、yarn start する。
５：今度は、うまく起動して、スタート画面が表示される。
　　しかしこの時、tsconfig.json の２１行目が、自動修正されている。
６：仕方ないのでコミット。
７：github desktop を起動する。
　　すると、プルリクしてねと、催促するボタンが表示される。
８：毎回、うざいので、ボタンを押してみた。（現状です）

**Comment by koyama223y** [comment]
フォークをせずに、ただ単に、クローンした場合で、
上記の現象が再現するかどうか、試してみました。
しかし、結果は変わらず、自動修正されてしまいます。

一瞬で消えてしまう、react-scripts からのメッセージをキャプチャしましたので添付します。
![image](https://user-images.githubusercontent.com/65491690/101243818-12591b00-3746-11eb-853a-71f67ade92b9.png)

**Comment by koyama223y** [comment]
[新しい JSX トランスフォーム](https://ja.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)

に、変更してくれると、助かります。
ただし、React v17からの新機能だそうです。

npm list --depth=0
を実行したところ、私のreact のバージョンは、
react@17.0.1
になっていました。

**Comment by koyama223y** [comment]
この現象は、私だけなのでしょうか？
ごくありふれた、普通の環境だと思うのですが・・・
npm uninstall -g create-react-app
または
yarn global remove create-react-app
も行いました。
つまり、最新の環境のはずなのだけれども、なんでかな？
原因がわからない。参りました。

**Comment by Syunki0403** [comment]
自分の環境でも、react-jsxに自動修正が入りました。
以前、同じ症状になった際に下記サイトを参考にしてエラーメッセージを消せたので、共有させていただきます。
ただ、以下のやり方は一時的なものなので対策の仕方としては正解ではないと思いますのでご了承ください。

https://www.reddit.com/r/react/comments/k0bw7y/compileroptionsjsx_must_be_reactjsx_to_support/

**Comment by mune-actor-en** [comment]
どうやらReact17では新しいJSXの変換サポートが追加されたみたいです:bulb:
react-jsx　（productionビルド用）
react-jsxdev　（developmentビルド用）
reactは旧変換となっていますが、ひとまず動作するようであればいったんこのままで進めたいと思います:pray:
今後課題になったら随時対応していく形でやっていければと！
https://zenn.dev/uhyo/articles/react17-new-jsx-transform

**Comment by koyama223y** [comment]
@mune-actor-en 
了解しました。
ただ、初心者＆初見者の方も、簡単に入ってこれるように、
時折、いったんプロジェクトフォルダを完全に削除して、
初見者さんと同じようにクローンしてみて、一から環境構築を試してみる
という作業も、大切な事かなと、思いました。

ちなみに私は、少なくとも２０回くらいは、クローンやフォークをし直して、
約７万個のファイルを削除したり、インストールし直したりで、ほんと大変でした。
ファイル７万個って、ちょっと、やばすぎですよね。
これでは、ウイルスやスパイソフトが紛れ込んでても、絶対、気づかないよね（笑）

**Comment by koyama223y** [comment]
@Syunki0403 
なるほど、貴重な情報をありがとう。
今、気を取り直して、リンク先のページの通り、やってみたら、うまくいきました。
結局、typescript のバージョンが、原因なんですね。
なので、package.json の dependencies を、
（変更前）"typescript": "^4.0.3",
（変更後）"typescript": "4.0.3",
にしたところ、うまくいきました。

変更前の設定だと、typescript の v4.1.2 がインストールされてしまって、
このバージョンだと、tsconfig.json の２１行目が、
"jsx": "react-jsx"
に、修正されてしまうのですね。

ということで、@むね さん
"typescript": "4.0.3"
または
"typescript": "^4.1.2"
の、どちらかに変更すると、いいかと思います。
後者にした場合は、恐らく、
"jsx": "react-jsx"
が、利用されることになるでしょう。
