### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by mune-actor-en** [mune92283498/uchinoko_project#4]

**Comment by y-mabuchi** [comment]
[DB設計](https://docs.google.com/spreadsheets/d/1c50qvS2qkYB_N9qxObqlTNuA8nbHwyJv-rPf52KJir0/edit?usp=sharing)

**Comment by y-mabuchi** [comment]
@gonta1026 
API同様、細かいところはもうちょっと打ち合わせたいですが、大枠は完成です

[DB設計](https://docs.google.com/spreadsheets/d/1c50qvS2qkYB_N9qxObqlTNuA8nbHwyJv-rPf52KJir0/edit#gid=1397539864)

**Comment by gonta1026** [comment]
@gonta1026 
[DB設計](https://docs.google.com/spreadsheets/d/1c50qvS2qkYB_N9qxObqlTNuA8nbHwyJv-rPf52KJir0/edit#gid=1347482306) 確認いたしました！
かなりいい感じだと思います！
一点、Userテーブルのtokenについてなのですが、毎回ログイン、サインインとで全く違うtokenが発行される予定です！
こちらは現状DBに保存をするつもりはなく、tokenを持っているか、いないかの判別だけするような形にしたいと思っていますがいかがでしょうか？？

**Comment by y-mabuchi** [comment]
なるほど、、、でしたらDBへの保存は必要ないですね、承知しました！

https://qiita.com/c6tower/items/4909948b6619dca6e82c

↑な感じですか？

https://programmagick.com/blogs/node_express_mysql_jwt/

↑も参考になりそうな感じが、、、

**Comment by gonta1026** [comment]
DBに保存させるパターンもあると思うのですが、このような形もやってみたいと思ってDBへの保存なしにしました！
なお、参考的にはこちらの記事です！
[【JWT（JSON Web Token）】Node.jsで実際に使ってみた](https://qiita.com/sa9ra4ma/items/67edf18067eb64a0bf40)

**Comment by y-mabuchi** [comment]
大枠は完成したので、今後は随時アップデートしていきます。
Closeします。
