### ISSUE TITLE
API設計

### ISSUE THREAD

**Issue by mune-actor-en** [mune92283498/uchinoko_project#5]

**Comment by mune-actor-en** [comment]
担当：ゆーすけさん

**Comment by y-mabuchi** [comment]
[API設計](https://docs.google.com/spreadsheets/d/1NooqiixyQu1sSjWP0EEvg5EtZQ2VVyo9havwkP56QHE/edit?usp=sharing)

**Comment by y-mabuchi** [comment]
@gonta1026 
もう少し細かく設計しようと思いますが、大枠はできました

[API設計](https://docs.google.com/spreadsheets/d/1NooqiixyQu1sSjWP0EEvg5EtZQ2VVyo9havwkP56QHE/edit#gid=256022739)

**Comment by gonta1026** [comment]
@y-mabuchi 
こちらも確認いたしました！
僕の方で確認をしたい項目をUserのタブのところに追加をさせていただきました！
こちらお手隙のタイミングでご確認よろしくお願いいたします！

**Comment by y-mabuchi** [comment]
@gonta1026 
確認ありがとうございました！


authのGETは無しにして、POSTをログインに想定したいと思います。
ですので、authのGETは削除しました。

usersのPOST:/api/v1/usersは、おっしゃるとおりサインアップを想定しています。
トークンを返却してもらって、フロントで保持する方向で承知しました！

**Comment by y-mabuchi** [comment]
大枠は完成したので、今後は随時アップデートしていきます。

下記を参照ください。
[API仕様wiki](https://github.com/mune-actor-en/uchinoko-project/wiki/API%E4%BB%95%E6%A7%98)

Closeします。
